# ParticleX Configuration
# https://github.com/theme-particlex/hexo-theme-particlex

# Avatar image
avatar: /images/IMG_1030.jpg

background:
    - /images/backgrounds/1.webp
    - /images/backgrounds/2.webp
    - /images/backgrounds/3.webp
    - /images/backgrounds/4.webp
    - /images/backgrounds/5.webp
    - /images/backgrounds/6.webp
    - /images/backgrounds/7.webp
    - /images/backgrounds/8.webp
    - /images/backgrounds/9.webp
    - /images/backgrounds/10.webp
    - /images/backgrounds/11.webp
    - /images/backgrounds/12.webp
    - /images/backgrounds/13.webp
    - /images/backgrounds/14.webp
    - /images/backgrounds/15.webp
    - /images/backgrounds/16.webp
    - /images/backgrounds/17.webp
    - /images/backgrounds/18.webp
    - /images/backgrounds/19.webp
    - /images/backgrounds/20.webp
    - /images/backgrounds/21.webp
    - /images/backgrounds/22.webp
    - /images/backgrounds/23.webp
    - /images/backgrounds/24.webp
    - /images/backgrounds/25.webp

loading: /images/loading.gif
# Optional colors for category and tag
colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com

# Main menu navigation
menu:
    Home:
        name: house
        theme: solid
        link: /
    About:
        name: id-card
        theme: solid
        link: /about
    Projects:
        name: code
        theme: solid
        link: /projects
    Archives:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags

# Side info card
card:
    enable: true
    description: |
        想像不到未來的自己可以幹嘛...
    iconLinks:
        GitHub:
            name: github
            theme: brands
            link: https://github.com/YCC1203
        osu!:
            name: gamepad
            theme: solid
            link: https://osu.ppy.sh/users/24565338
    friendLinks:

# Footer info
footer:
    since: 2022
    # Customize the server domain name ICP
    ICP:
        enable: false
        code:
        link:

# Polyfill
# https://polyfill.io
polyfill:
    enable: false
    features:
        - default

# Highlight.js
# https://highlightjs.org
highlight:
    enable: true
    style: github

# KaTeX math rendering
math:
    enable: false

# Image preview
preview:
    enable: true

# Article encryption
crypto:
    enable: false

# Search
search:
    enable: true

# giscus
# https://github.com/giscus/giscus
giscus:
    enable: true
    src: https://giscus.app/client.js
    repo: YCC1203/YCC1203.github.io
    repoID: R_kgDOJifRFA
    category: Announcements
    categoryID: DIC_kwDOJifRFM4CW3Hj
    mapping: url
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: top
    theme: light
    lang: zh-TW

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
    proxy: # CORS proxy

# Waline
# https://github.com/walinejs/waline
waline:
    enable: false
    serverURL: # Waline server address url, you should set this to your own link
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.2.0/weibo
        - https://unpkg.com/@waline/emojis@1.2.0/alus
        - https://unpkg.com/@waline/emojis@1.2.0/bilibili
        - https://unpkg.com/@waline/emojis@1.2.0/qq
        - https://unpkg.com/@waline/emojis@1.2.0/tieba
        - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
    lang: # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
    enable: false
    envID:
    region:
    path: location.pathname
    lang:
